/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package domain.naming.system;

import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.awt.event.*;
import javax.swing.border.*;

/**
 *
 * @author Shano
 */
public class insert extends javax.swing.JFrame {

    /**
     * Creates new form insert
     */
    public insert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfdname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfclass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 150, 1000, 400));
        setMinimumSize(new java.awt.Dimension(1000, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 130, 40));

        searchbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchbtn.setText("Save");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 120, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Insert Domain Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));
        getContentPane().add(tfdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 240, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insert IP Address:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));
        getContentPane().add(tfip, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 240, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Class:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Insert Data");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));
        getContentPane().add(tfclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 160, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shano\\Documents\\NetBeansProjects\\Domain Naming System\\src\\domain\\naming\\system\\icons\\blankkk.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Find Domain");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            menu su = new menu();
            su.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    public static boolean isValidIPAddress(String ipAddress) {
        String[] octets = ipAddress.split("\\.");

        if (octets.length != 4) {
            return false; // IPv4 address should consist of 4 octets
        }

        for (String octet : octets) {
            try {
                int octetValue = Integer.parseInt(octet);
                if (octetValue < 0 || octetValue > 255) {
                    return false; // Each octet should be between 0 and 255
                }
            } catch (NumberFormatException e) {
                return false; // Invalid number format in an octet
            }
        }

        return true; // Passed all validations, it's a valid IPv4 address
    }
public static String getIPAddressClass(String ipAddress) {
        String[] octets = ipAddress.split("\\.");

        if (octets.length != 4) {
            return "Invalid IP Address"; // IPv4 address should consist of 4 octets
        }

        int firstOctet;
        try {
            firstOctet = Integer.parseInt(octets[0]);
        } catch (NumberFormatException e) {
            return "Invalid Octet"; // Invalid number format in the first octet
        }

        if (firstOctet >= 1 && firstOctet <= 126) {
            return "A"; // Range: 1.0.0.0 to 126.255.255.255
        } else if (firstOctet >= 128 && firstOctet <= 191) {
            return "B"; // Range: 128.0.0.0 to 191.255.255.255
        } else if (firstOctet >= 192 && firstOctet <= 223) {
            return "C"; // Range: 192.0.0.0 to 223.255.255.255
        } else if (firstOctet >= 224 && firstOctet <= 239) {
            return "D"; // Range: 224.0.0.0 to 239.255.255.255
        } else if (firstOctet >= 240 && firstOctet <= 255) {
            return "E"; // Range: 240.0.0.0 to 255.255.255.255
        } else {
            return "Unknown Class";
        }
    }

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
     
        String dname = tfdname.getText();
        String ip = tfip.getText();
        String clas = getIPAddressClass(ip);
        
        if( isValidIPAddress(ip))
        {
            try
            {
                Conn con = new Conn();
            
                String sql = "insert into data2(ip, dname, class) values(?, ?, ?)";
		PreparedStatement st = con.c.prepareStatement(sql);

		st.setString(1, tfip.getText());
                st.setString(2, tfdname.getText());
		st.setString(3, clas);
                
		int i = st.executeUpdate();
		if (i > 0)
                {
                    JOptionPane.showMessageDialog(null, "Domain Added Successfully.");
                }
                
                ResultSet rs;
                rs = con.s.executeQuery("select * from data2 where ip = '"+ip+"'");
                    if(rs.next()){
                        tfclass.setText(rs.getString(4));
                    }
			
                        }catch(Exception e){
                                System.out.println(e);
                 }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Invalid IP Address");
        }
        
         
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField tfclass;
    private javax.swing.JTextField tfdname;
    private javax.swing.JTextField tfip;
    // End of variables declaration//GEN-END:variables
}
